# AIM: Implementing Cost-based Deterministic Minimizaton function to find the nearest docking / d-point. 

import math
from typing import List

from src.common.logging import logger
from src.common.environment.mock_env import MockEnvironmentModel
from src.common.entity.position import Waypoint

from src.fly.stage3_decision.entity import DumpConfig

from src.fish.stage3_action.entity import CostModel


# When Pybullet is ready, implement the below code.
"""
from src.fish.stage3_action.environment.pybullet_env import PyBulletEnvironmentModel

self.env_model = PyBulletEnvironmentModel(
    current_field=current_field,
    obstacle_map=obstacle_map,
    localization_estimator=localizer,
)
"""

class PathCostCalculator:
    def __init__(self, cost_model_cfg: CostModel, dump_points: List[DumpConfig]):
       self.cfg = cost_model_cfg
       
       self.weights = self.cfg.cost_weigths
       self.vehicle = self.cfg.vehicle_model
       self.norm_limits = self.cfg.normalization_limits
       self.dump_points = dump_points
       
       self.env_model = MockEnvironmentModel(current= 0.5, risk= 0.2, uncertainity= 0.1)



    def planar_distance(self, current: Waypoint, target: Waypoint) -> float:
        planar_distance = math.hypot(target.x - current.x, target.y - current.y)
        #logger.info(f"PathCostCalculator -> planner_distance(): ENDS, distance: {planar_distance}")
        return planar_distance
    


    def normalize(self, value: float, max_value: float) -> float:
        normalized_val = value / max_value
        #logger.info(f"PathCostCalculator -> normalize(): ENDS, norm value: {normalized_val}")
        return min(normalized_val, 1.0) 



    def calculate_docking_cost(self, target_pos: Waypoint, current_pos: Waypoint) -> float:
        try:
            #logger.info(f"PathCostCalculator -> calculate_docking_cost(): STARTS, calculating for d_point: {target_pos}")
      
            # distance and time
            distance = self.planar_distance(current_pos, target_pos)
            #travel_time = distance / self.vehicle.cruise_speed

            # current opposition
            current_cost = self.env_model.current_opposition(current_pos, target_pos)

            # drag and energy
            relative_speed = self.vehicle.cruise_speed + current_cost
            energy = self.vehicle.drag_coeff * (relative_speed ** 2) * distance
            drag = self.vehicle.avg_drag_force * distance

            # safety 
            risk = self.env_model.obstacle_density(target_pos)
            uncertainty = self.env_model.localization_uncertainty()

            # normalize
            travel_time_n = self.normalize(distance, self.norm_limits.max_distance)           # time = distance/speed, norm(time) = norm(ditance) as speed will be nullify in division. 
            current_n = self.normalize(current_cost, self.norm_limits.max_current)
            energy_n = self.normalize(energy, self.norm_limits.max_energy)
            risk_n = self.normalize(risk, self.norm_limits.max_risk)
            uncertainty_n = self.normalize(uncertainty, self.norm_limits.max_uncertainty)

            # weighted sum
            total_cost = (
                self.weights.travel_time * travel_time_n +
                self.weights.current * current_n +
                self.weights.energy * energy_n +
                self.weights.drag * drag +
                self.weights.risk * risk_n +
                self.weights.uncertainty * uncertainty_n
            )

            #logger.info(f"PathCostCalculator -> calculate_docking_cost(): ENDS, cost: {total_cost}")
            return total_cost


        except Exception as e:
            logger.info(f"Error occurred in PathCostCalculator -> calculate_docking_cost(), error: {e}")
            raise e
        


    def find_best_dump_point(self, current_position: Waypoint, locked_dump_ids: List[int]) -> DumpConfig:
        try:
            logger.info(f"PathCostCalculator -> find_best_dump_point(): STARTS, locked_dumps: {locked_dump_ids}")

            # NOTE: If a dispatch order for collection of certain dump point is generated by Fly, Fish machine should not unload self bin in that dump for now.
            available_dumps = [dump for dump in self.dump_points if dump.dump_id not in locked_dump_ids]

            logger.info(f"PathCostCalculator -> find_best_dump_point(), no. of available dumps: {len(available_dumps)}")

            # Finding the best dump point, after calculating cost for all the dump points(for now 8 dumps are present).          
            best_docking_point = min(available_dumps, key= lambda d_pt : self.calculate_docking_cost(target_pos = d_pt.position, current_pos = current_position))                                                                                                
            
            logger.info(f"PathCostCalculator -> find_best_dump_point(): ENDS, Best_docking_point is : {best_docking_point}")
            return best_docking_point


        except Exception as e:
            logger.info(f"Error occurred in PathCostCalculator -> find_best_dump_point(), error: {e}")
            raise e