# NOTE (v1 MVP):
# Underwater path is generated by reversing surface coverage.
# This will be replaced by depth-aware and flow-aware planning in later versions.

import math
from typing import List, Dict, Any

from src.common.logging import logger
from src.common.projection.entity import WorldObject

from src.fish.stage3_action.entity import Waypoint, Navigation, Speeds



class PathNavigator:
    """
    Helps in Fish's machine navigation. 
    """
    def __init__(self, navigation_cfg: Navigation):
        self.navigation_cfg = navigation_cfg
        self.speeds: Speeds  = navigation_cfg.speeds
        self.sweep_step: float = navigation_cfg.sweep_step
        self.current_position: Waypoint = navigation_cfg.start_point
        self.reach_threshold: float = navigation_cfg.reach_threshold                        # To check target is in reach or not for Fish machine

        self.path: List[Waypoint] = []
        self.current_index: int = 0                                                         # No. of waypoints crossed in the set path.
        self.curr_speed: float = self.speeds.surface
        self.dt = 1.0
        self.paused: bool = False

        self.trajectory: list[Dict[Any, Any]] = []
        self.step_count: int = 0



    def set_path(self, depth: float, start_position: Waypoint):
        try:
            logger.info(f"PathNavigator -> set_path(): STARTS, depth: {depth}")

            # Generate SURFACE path once.
            if not self.path or len(self.path) == 0:
                self.path = self.generate_lawnmower_path(cleaning_depth = 0.0)

            # NOTE: UNDERWATER path = Reversed cached SURFACE path + project to depth.
            # SURFACE LEVEL path is generted first, then UNDERWATER LEVEL.
            if depth < 0:
                rev_surface_path = list(reversed(self.path)) 
                active_path = [Waypoint(wp.x, wp.y, depth) for wp in rev_surface_path]                                       
            else:
                active_path = self.path
             
            # Updating path parameters for the current operation level.
            self.path = active_path
            self.current_position = start_position
            self.current_index = 0                                                      # to avoid index error if path is not generated.
            self.paused = False

            logger.info(f"PathNavigator -> set_path(): ENDS, active path: {self.path}")
            return 


        except Exception as e:
            logger.info(f"Error occurred in PathNavigator -> set_path(), error: {e}")
            raise e



    def generate_lawnmower_path(self, cleaning_depth: float) -> List[Waypoint]:
        """
        Generates the `Lawn mower path` pattern, the chosen navigation pattern for the Fish machine.

        ONLY generates surface-style lawnmower path.
        ```
            [----------------                  
            ----------------]
            [----------------                  
            ----------------]
            [----------------                  
            ----------------]
            [----------------                  
            ----------------]

            (brackets are turns)
        ```
        
        :param self: Belongs to the PathNavigator class.
        :param cleaning_depth: Depth of workspace of current operation. 
        :type cleaning_depth: float
        :return: List of waypoint in the Lawn-mower path.
        :rtype: List[Waypoint]
        """
        try:
            logger.info(f"PathNavigator -> generate_lawn_mower_path(): STARTS, cleaning_depth: {cleaning_depth}")
            
            path: List[Waypoint] = []

            # Defining boundary of workspace.
            x_start, y_start = self.navigation_cfg.start_point.x, self.navigation_cfg.start_point.y
            x_end, y_end = self.navigation_cfg.end_point.x, self.navigation_cfg.end_point.y

            direction: int = 1
            y_curr: float = y_start

            while y_curr <= y_end:                                              # (eg: 0 < 100, 20 < 100, 100 = 100)
                # Moving forward in x-axis
                if direction == 1:                                              
                    path.append(Waypoint(x_start, y_curr, cleaning_depth))      # x -> 0,       y -> 0
                    path.append(Waypoint(x_end, y_curr, cleaning_depth))        # x -> 100,     y -> 0

                # Moving backward in x-axis
                else:                                                           
                    path.append(Waypoint(x_end, y_curr, cleaning_depth))        # x -> 100,     y -> 5
                    path.append(Waypoint(x_start, y_curr, cleaning_depth))      # x -> 0,       y -> 5

                # Moving in y-axis, by 1 sweep step, to reach towards end point.
                y_curr += self.sweep_step    

                # Reversing the direction of fish machine.   
                direction *= -1                 
                

            logger.info(f"PathNavigator -> generate_lawn_mower_path(): ENDS")
            return path


        except Exception as e:
            logger.info(f"Error occurred in PathNavigator -> generate_lawnmower_path(), error: {e}")
            raise e



    def pause(self):
        try:
            logger.info(f"PathNavigator -> pause(): STARTS")
            self.paused = True
            logger.info(f"PathNavigator -> pause(): ENDS")


        except Exception as e:
            logger.info(f"Error occurred in PathNavigator -> pause(), error: {e}")
            raise e


    
    def resume(self):
        try:
            logger.info(f"PathNavigator -> resume(): STARTS")
            self.paused = False
            logger.info(f"PathNavigator -> resume(): ENDS")


        except Exception as e:
            logger.info(f"Error occurred in PathNavigator -> resume(), error: {e}")
            raise e
        



    def target_is_near(self, world_obj: WorldObject) -> bool:
        """
        Decide if target is close enough to execute manipulation.
        """
        try:
            logger.info(f"PathNavigator -> target_is_near(): STARTS, world object: {world_obj}")

            target_is_near = world_obj.distance <= self.reach_threshold

            logger.info(f"PathNavigator -> target_is_near(): ENDS, target_is_near: {target_is_near}")
            return target_is_near
        
        except Exception as e:
            logger.info(f"Error occurred in PathNavigator -> target_is_near(), error: {e}")
            raise e
    


    def get_next_position(self) -> Waypoint:
        """
        Navigation is the authoritative source of robot motion.

        All position updates are computed here and passed to the simulation layer for execution. 
        
        This avoids conflicting motion models and keeps planning logic centralized.
        
        :param self: Belongs to the PathNavigator class
        :param dt: The time diffrence for calculating step_distance/incremental motion
        :type dt: float
        :return: Returns confirmation where the Fish machine stepped forward or not.
        :rtype: bool
        """
        try:
            logger.info(f"PathNavigator -> get_next_position(): STARTS")
         
            # 1. Recognize the next target waypoint in the set path.
            target_waypoint = self.path[self.current_index]
            logger.info(f"PathNavigator -> get_next_position(): current index: {self.current_index}, current position: {self.current_position}, target position: {target_waypoint}")

            # 2. Calculate direction vectors (3D)
            dx = target_waypoint.x - self.current_position.x
            dy = target_waypoint.y - self.current_position.y
            dz = target_waypoint.z - self.current_position.z

            # Distance between current position and the next target waypoint(not new position)
            distance = math.sqrt(dx*dx + dy*dy + dz*dz)
            logger.info(f"PathNavigator -> get_next_position(): Distance between current position and the next target waypoint: {distance}")

            # 3. Compute step distance, using formula [distance = speed * time]
            step_distance = self.curr_speed * self.dt

            # 4. If already reached very close to target and might overshoot in stepping, then snap to target waypoint and then approach next waypoint.
            if distance <= step_distance:
                
                # Snap to the current target first
                self.current_position = target_waypoint   
                self.log_trajectory_point()                                                                 # To avoid missing logging the snapped waypoint

                # Advance the current index
                self.current_index += 1

                # Check if path is finished, then return the last current position / target waypoint, to avoid index out of range error.
                if self.path_is_finished():                                                                 # refer ACTION_NOTES.md(9)
                    logger.info(f"PathNavigator -> get_next_position(): Current set path is finished, return current position")
                    return self.current_position                            

                # If current path is not finished, then set the next waypoint in the path as target.
                target_waypoint = self.path[self.current_index]             

                # Calculate direction vectors (3D) again for the new target.
                dx = target_waypoint.x - self.current_position.x
                dy = target_waypoint.y - self.current_position.y
                dz = target_waypoint.z - self.current_position.z

                distance = math.sqrt(dx*dx + dy*dy + dz*dz)
                logger.info(f"PathNavigator -> get_next_position(): New distance between current and target: {distance}")


            # 5. Normalize directions
            ux = dx / distance
            uy = dy / distance
            uz = dz / distance

            # 6. Incremental motion
            new_x = self.current_position.x + ux * step_distance
            new_y = self.current_position.y + uy * step_distance
            new_z = self.current_position.z + uz * step_distance

            # 7. New position for Fish machine
            new_position = Waypoint(new_x, new_y, new_z)

            logger.info(f"PathNavigator -> get_next_position(): ENDS, new_position: {new_position}")
            return new_position
        
        
        except Exception as e:
            logger.info(f"Error occurred in PathNavigator -> get_next_position(), error: {e}")
            raise e



    def path_is_finished(self) -> bool:
        try:
            logger.info(f"PathNavigator -> path_is_finished(): STARTS")

            path_is_finished = self.current_index >= len(self.path)

            logger.info(f"PathNavigator -> path_is_finished(): ENDS, path_is_finished: {path_is_finished}")
            return path_is_finished
        

        except Exception as e:
            logger.info(f"Error occurred in PathNavigator -> path_is_finished(), error: {e}")
            raise e

     

    # NOTE: Can be refactored into TrajectoryLogger service in future
    def log_trajectory_point(self):
        try:
            logger.info(f"PathNavigator -> log_trajectory_point(): STARTS")

            # Determining the operation level of the Fish machine
            operation_level = "surface" if self.current_position.z >= 0 else "underwater"

            self.trajectory.append({
                "current_position": self.current_position,
                "operation_level": operation_level,
                "step_taken": self.step_count
            })

            logger.info(f"PathNavigator -> log_trajectory_point(): ENDS")
            return


        except Exception as e:
            logger.info(f"Error occurred in PathNavigator -> log_trajectory_point(), error: {e}")
            raise e