# This file contains Simulation configurations for the Fish module



visualization:
  enabled_gui: true

record_output: false                                          # enabling Simulation video recording. To unlock this feature, `enabled_gui` in Visualization config must be `true`.

grasp_threshold: 3.0


spawning:

  visual:
    machines:

      - name: fish_machine
        shape: box
        size:  [1.0, 0.4, 0.4]                                # [height, breadth, width]
        color: [0.18, 0.18, 0.18, 1.0]                        # black
        count: 10

      - name: manatee_machine
        shape: box
        size: [3.0, 1.2, 1.2]                                 
        color: [1.0, 1.0, 1.0, 1.0]                           # white
        count: 10

    targets:

      - name: garbage
        shape: sphere
        size: [0.30]
        color: [1.0, 0.0, 0.0, 1.0]                           # red
        count: 10

      - name: collected                                       # not used for now
        shape: sphere
        size: [0.30]
        color: [0.0, 1.0, 0.0, 1.0]                           # green
        count: 0

    entities:

      - name: fish
        shape: capsule
        size: [0.15, 0.60]                                    # radius, height
        color: [0.0, 1.0, 1.0, 1.0]                           # cyan
        count: 6

      - name: plant
        shape: box
        size: [0.2, 0.2, 0.6]                                 # x,y,z
        color: [0.0, 0.5, 0.0, 1.0]                           # dark green
        count: 8

    hazards:

      - name: big_rock
        shape: box
        size: [0.8, 0.8, 0.6]
        color: [0.45, 0.3, 0.15, 1.0]                         # brown
        count: 4

      - name: dangerous_animal
        shape: capsule
        size: [0.45, 1.80]                                    # radius, height            # 3 times larger than fish
        color: [0.0, 1.0, 0.0, 1.0]                           # yellow
        count: 3


  zones:                                                      # NOT USED CURRENTLY

    targets:
      x_range: [5, 6]
      y_range: [-1, 1]
      z: 0
      min_distance: 1.0

    entities:
      x_range: [-5, 5]
      y_range: [-5, 5]
      z: 0
      min_distance: 1.0

    hazards:
      x_range: [-6, 6]
      y_range: [-6, 6]
      z: 0
      min_distance: 1.5