# This file contains configurations for the Fish vision model's configurations
# Models used: YOLOv8s

visualization:
  enabled_gui: true


io:
  source: folder_video                                       # camera | video | sim | folder_video          # refer VISION_NOTES.md(5)
  camera: 
    device_id: 0
  video:
    path: dataset/test_footage_split                                                                        # refer dataset/NOTE.md(4)


class_names:
  - algae_bloom
  - big_rock
  - crab
  - dangerous_animal
  - fish
  - fishing_net
  - fishing_rope
  - glass_bottle
  - human
  - jellyfish
  - metal_can
  - plastic_bag
  - plastic_bottle
  - starfish
  - turtle


training: 
  model_name: model/yolov8s.pt
  model_parameters:
    data: dataset/Marine-project-3/data.yaml
    imgsz: 640
    epochs: 100
    batch: 16
    device: cpu
    optimizer: AdamW
    patience: 30
    lr0: 0.001
    project: src/fish/stage1_vision/model_result                   # specify location to save trained YOLO model's weights here 
    name: Fish_V1


inference:
  weights: src/fish/stage1_vision/model_result/Fish_V1/weights/best.pt
  conf: 0.4
  imgsz: 640
  verbose: false


tracking:
  enabled: true
  tracker: botsort.yaml
  persist: true
  verbose: false


aggregation:
  max_history: 15
  stable_age: 5                                                 # Number of frames, an object must appear to be considered stable
  max_idle_frames: 30                                           # Nuber of frames, an object is not seen


# Semantic categories
categories:
  collection_targets:
    - algae_bloom
    - fishing_net
    - fishing_rope
    - glass_bottle
    - metal_can
    - plastic_bag
    - plastic_bottle

  environmental_entities:
    - human
    - fish
    - crab
    - jellyfish
    - starfish
    - turtle

  navigation_hazards:
    - dangerous_animal
    - big_rock