# This file contains configurations for the Fly action logic configurations


controller:
  home:
    x: 50.0
    y: 50.0
    z: 10.0        # hover height


monitor:
  timeout_sec: 300.0
  freeze_sec: 100.0


